backend:
  name: git-gateway
  branch: main # Si usas otra rama, cámbiala aquí

media_folder: "img"
public_folder: "/img" 

collections:
  - name: "productos"
    label: "Catálogo de Productos"
    files:
      - file: "productos.js"
        label: "Lista de Productos"
        name: "productosList"
        fields:
          - label: "Lista de Productos"
            name: "productos"
            widget: "list"
            summary: "{{fields.nombre}} - $ {{fields.precio}}"
            fields:
              - {label: "ID Único", name: "id", widget: "string", required: true, hint: "Ej: CR001 (No cambiar después de crear)"}
              - {label: "Nombre del Producto", name: "nombre", widget: "string", required: true}
              - {label: "Precio (sin signo $)", name: "precio", widget: "number", value_type: "int", required: true, min: 1}
              - {label: "Imagen del Producto", name: "imagen", widget: "image", required: true, hint: "Sube una foto aquí"}
              - {label: "Detalles / Tallas", name: "detalles", widget: "string", required: false}
